### ISSUE TITLE
Calculating partial derivatives #19_intro_to_machine_learning

### ISSUE THREAD

**Issue by sniafas** [ThanosTagaris/python_ml_tutorial#1]
Thanks for this amazing repo
Just a question about the derivative calculation.

I have written a function in order to reproduce the partial derivative equation,

    w = np.random.random()
    b = np.random.random()
    def compute_derivatives(x,y):

    dw = 0
    db = 0
    a = 0.02
    N = len(x)
    for i in range(N):
        x_i = x[i]
        y_i = y[i]
        y_hat = predict(x_i)
        dw += -(2/N) * x_i * (y_i - y_hat)        
        db += -(2/N) * (y_i - y_hat)
    w = w - (a*dw)
    b = b - (a*db)

but the mse increases for some reason. When I use your method

    dw = - (2 / sum(x)) * sum(x * (y - y_hat))
    db = - (2 / sum(x)) * sum(y - y_hat)

it runs as supposed to be. Can you elaborate on that?

**Comment by djib2011** [comment]
Hi, thanks for the kind words!

Your MSE keeps increasing because you're taking too large steps. The learning rate (parameter `a`) you're using is too large. I actually made a mistake in the computation of the gradient, it should be:

```python
dw = - (2 / len(x)) * sum(x * (y - y_hat))
db = - (2 / len(x)) * sum(y - y_hat)
```

This causes the partial derivatives `dw` and `db` to be much larger, which is the reason for the smaller learning rates. I fixed the issue and re-uploaded the notebook; it should be working fine now.

Regarding your function, if you decrease the learning rate by a couple of orders of magnitude it should work well. 

One thing I don't understand (unrelated to the gradient computation) is how your function does the assignments, i.e. `w = w - a * dw` (I'm assuming that this is inside the body of the function - I can't tell because github messed up the indentation in your post). Since you are assigning a value to `w`, the interpreter should think that `w` is a local variable of this function, which means that it should raise a `NameError` because it thinks that `w` is undeclared when trying to add it to itself. I'm not sure how this works for you without declaring the two variables as global, i.e. `global w, b`.

**Comment by sniafas** [comment]
Hi, thank you for the turnaround.
You are right, the lr magnitute was the reason that partial derivative calculations didn't work. And along with the `sum(x)` and the same lr from your example were driven me mad.

Sorry if it was confusing, w and b are in the scope of function, just github indentation rules.
Thanks anyway!
